services:
  mysql:
    image: mysql:8.4
    container_name: chore-share-mysql
    environment:
      MYSQL_DATABASE: chore_share
      MYSQL_USER: chore_share
      MYSQL_PASSWORD: chore_share_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - chore-share-mysql-data:/var/lib/mysql

volumes:
  chore-share-mysql-data: